name: dependency
description: "A new Flutter project."
version: 0.0.1
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  state:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: state
  package:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: package
  rpx:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: rpx
  ui_app:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_app
  ui_page:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_page
  fn_nav:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: fn_nav
  ui_theme:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_theme
  ui_button:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_button
  ui_toast:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_toast
  font_awesome_flutter: ^10.12.0
  logger:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: logger

dev_dependencies:
  #flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec