name: fn_device
description: A new Flutter project.
version: 0.1.1
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  device_info_plus: ^12.3.0
  crypto: ^3.0.7

dev_dependencies:
  very_good_analysis: ^10.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
