name: fn_auth
description: A new Flutter project.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  shared_preferences: ^2.5.4
  fn_security:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: fn_security
    #path: /Users/huazhimeng/Desktop/flutter_ui/security

dev_dependencies:
  very_good_analysis: ^10.1.0
  test: ^1.25.6