name: fn_security
description: A new Flutter project.
version: 0.1.0
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  crypto: ^3.0.7
  encrypt: ^5.0.3
  fn_device:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: fn_device
  logger:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: logger

dev_dependencies:
  very_good_analysis: ^10.1.0
