name: state
description: A new Flutter project.
version: 0.6.2
homepage: flutter_ui

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^5.0.0
  very_good_analysis: ^10.0.0

flutter:
