name: fn_storage
description: A new Flutter project.
version: 0.1.1
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  shared_preferences: ^2.5.4

dev_dependencies:
  very_good_analysis: ^10.1.0
