name: logger
description: A sample command-line application with basic argument parsing.
version: 0.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:

dev_dependencies:
  # lints: ^6.0.0
  very_good_analysis: ^10.0.0
  test: ^1.25.6
