name: logger
description: A sample command-line application with basic argument parsing.
version: 0.0.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:

dev_dependencies:
  # lints: ^6.0.0
  very_good_analysis: ^10.1.0
