name: ui_upload
description: "A new Flutter project."
version: 0.0.1
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  #kit:
  #  path: ../kit
  ui_pick_file:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_pick_file
  ui_toast:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_toast
  ui_cache_image:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_cache_image
  nav:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: nav
  ui_photo_view:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_photo_view
  ui_alert:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_alert
  #api:
  #  path: ../../app/api

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^5.0.0
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
